version: '3.7'
services:
  nginx:
    image: nginx:1.22-alpine
    container_name: nginx
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./common:/etc/nginx/common
      - ./vhost:/etc/nginx/vhost
      - ./ssl:/etc/nginx/ssl
      - /data/logs/nginx:/var/log/nginx
