version: '3.7'
services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    restart: always
    volumes:
      - /data/db/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--default-time-zone=+8:00"]
