version: '3'
services:
  mssql-server-linux:
    container_name: mssql-server-linux
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
