version: '3.7'
services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    volumes:
      - /data/db/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass password
